version: "3"
name: "cardz"

services:
  postgres:
    image: "postgres:15.3"
    volumes:
      - ./backend/services/postgres/data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_MAPPED_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_KEYCLOAK_DB}
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_KEYCLOAK_DB_USER} -d ${POSTGRES_KEYCLOAK_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: ["start-dev", "--import-realm"] #sort out how to setup kc configuration for production later
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: ${POSTGRES_KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_HTTP_RELATIVE_PATH: /auth #logging into adminpanel doesn't seem to work without this
      KC_HEALTH_ENABLED: true
    volumes:
      - ./backend/services/keycloak/imports:/opt/keycloak/data/import
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${KEYCLOAK_MAPPED_PORT}:8080"
    #healthcheck:
      #test: ["CMD-SHELL", "bash ./backend/services/keycloak/scripts/healthcheck.sh"]
      #interval: 10s
      #timeout: 5s
      #retries: 5

  echo:
    build: ./backend/services/echo
    ports:
      - "10102:8080"
    depends_on:
      - keycloak
